# Generated by Django 6.0.3 on 2026-04-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('turno_ingreso', models.DateTimeField()),
                ('turno_salida', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=250, null=True)),
                ('estado', models.CharField(default='En curso', max_length=20)),
            ],
            options={
                'db_table': 'Asistencia',
                'managed': True,
            },
        ),
    ]
