# Generated by Django 6.0.3 on 2026-04-05 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asistencia', '0001_initial'),
        ('empleados', '0001_initial'),
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='id_empleado',
            field=models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='empleados.empleado'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='id_ubicacion',
            field=models.ForeignKey(db_column='id_ubicacion', on_delete=django.db.models.deletion.DO_NOTHING, to='ubicaciones.ubicaciones'),
        ),
    ]
