# Generated by Django 5.2.6 on 2025-09-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=150, unique=True)),
                ('password', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=150)),
                ('estado', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Usuarios',
                'managed': False,
            },
        ),
    ]
