# Generated by Django 6.0.3 on 2026-04-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('password_temp', models.BooleanField(default=True)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
