# Generated by Django 5.2.6 on 2025-10-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=200)),
                ('email', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=150, unique=True)),
                ('cedula', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50, unique=True)),
                ('telefono', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=250, null=True)),
                ('fecha_contratacion', models.DateField()),
            ],
            options={
                'db_table': 'Empleado',
                'managed': False,
            },
        ),
    ]
