# Generated by Django 6.0.3 on 2026-04-05 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('cedula', models.CharField(max_length=50, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_contratacion', models.DateField()),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Empleado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmpleadosAuditoria',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_email', models.CharField(blank=True, db_column='usuario_email', max_length=255, null=True)),
                ('accion', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre_completo', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('cedula', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_contratacion', models.DateField(blank=True, null=True)),
                ('empleado', models.ForeignKey(blank=True, db_column='empleado_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='empleados.empleado')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuentas.usuarios')),
            ],
            options={
                'db_table': 'Empleados_Auditoria_TB',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HorasExtras',
            fields=[
                ('id_hora_extra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cantidad_horas', models.DecimalField(db_column='cantidad_horas', decimal_places=2, max_digits=5)),
                ('justificacion', models.CharField(blank=True, max_length=500, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='empleados.empleado')),
            ],
            options={
                'db_table': 'HorasExtras',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HorasExtrasAuditoria',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_email', models.CharField(blank=True, max_length=255, null=True)),
                ('accion', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('empleado_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('empleado_cedula', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('cantidad_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('justificacion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('empleado', models.ForeignKey(blank=True, db_column='empleado_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.empleado')),
                ('hora_extra', models.ForeignKey(blank=True, db_column='hora_extra_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='empleados.horasextras')),
            ],
            options={
                'db_table': 'HorasExtras_Auditoria_TB',
                'managed': True,
            },
        ),
    ]
