# Generated by Django 6.0.3 on 2026-04-05 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaUsuario',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_empleado', models.IntegerField(null=True)),
                ('id_rol', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=150, null=True)),
                ('estado', models.CharField(max_length=50, null=True)),
                ('usuario_accion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_accion', to='cuentas.usuarios')),
                ('usuario_afectado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_afectado', to='cuentas.usuarios')),
            ],
            options={
                'db_table': 'USUARIOS_AUDITORIA_TB',
                'ordering': ['-fecha'],
            },
        ),
    ]
