# Generated by Django 5.2.6 on 2025-09-30 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('id_rol', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaUsuario',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_empleado', models.IntegerField(null=True)),
                ('id_rol', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=150, null=True)),
                ('estado', models.CharField(max_length=50, null=True)),
                ('usuario_accion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_accion', to='usuarios.usuario')),
                ('usuario_afectado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_afectado', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'USUARIOS_AUDITORIA_TB',
                'ordering': ['-fecha'],
            },
        ),
    ]
