# Generated by Django 6.0.3 on 2026-04-05 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteIncidente',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('accidente-trabajo', 'Accidente de trabajo'), ('fallo-equipamiento', 'Fallo de equipamiento'), ('incidente-seguridad', 'Incidente de seguridad'), ('problema-ambiental', 'Problema ambiental'), ('otros-eventos', 'Otros eventos')], max_length=50)),
                ('foto', models.ImageField(blank=True, db_column='archivo', null=True, upload_to='incidentes/')),
                ('fecha_evento', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.DO_NOTHING, related_name='reportes_incidentes', to='empleados.empleado')),
            ],
            options={
                'db_table': 'ReporteIncidentes',
                'managed': True,
            },
        ),
    ]
