# Generated by Django 6.0.3 on 2026-04-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cita', models.DateField(db_column='fecha_cita')),
                ('hora_inicio', models.TimeField(db_column='hora_inicio')),
                ('hora_finalizacion', models.TimeField(blank=True, db_column='hora_finalizacion', null=True)),
                ('motivo', models.CharField(blank=True, db_column='motivo', max_length=200, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', null=True)),
            ],
            options={
                'db_table': 'Citas',
                'managed': True,
            },
        ),
    ]
