# Generated by Django 6.0.3 on 2026-04-05 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes'),
        ),
    ]
