# Generated by Django 5.2.6 on 2025-09-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
                ('descripcion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=250, null=True)),
            ],
            options={
                'db_table': 'Roles',
                'managed': False,
            },
        ),
    ]
