# Generated by Django 6.0.3 on 2026-04-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'Roles',
                'managed': True,
            },
        ),
    ]
