# Generated by Django 6.0.3 on 2026-04-05 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('cedula', models.CharField(max_length=50, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.BooleanField(db_column='estado', default=True)),
                ('id_ubicacion', models.ForeignKey(blank=True, db_column='id_ubicacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ubicaciones.ubicaciones')),
            ],
            options={
                'db_table': 'Clientes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClientesAuditoria',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_email', models.CharField(blank=True, db_column='usuario_email', max_length=255, null=True)),
                ('accion', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre_completo', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('cedula', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('residencia', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente', models.ForeignKey(blank=True, db_column='cliente_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='clientes.clientes')),
            ],
            options={
                'db_table': 'Clientes_Auditoria_TB',
                'managed': True,
            },
        ),
    ]
