# Generated by Django 5.2.6 on 2025-09-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientesAuditoria',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_email', models.CharField(blank=True, db_column='usuario_email', max_length=255, null=True)),
                ('accion', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre_completo', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('cedula', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('residencia', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'CLIENTES_AUDITORIA_TB',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=200)),
                ('email', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=150, unique=True)),
                ('cedula', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50, unique=True)),
                ('telefono', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
                ('residencia', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Clientes',
                'managed': True,
            },
        ),
    ]
