# Generated by Django 5.2.6 on 2025-09-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=200)),
                ('email', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=150, unique=True)),
                ('cedula', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50, unique=True)),
                ('telefono', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
                ('residencia', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Clientes',
                'managed': False,
            },
        ),
    ]
