# Generated by Django 5.2.6 on 2025-09-24 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'managed': True},
        ),
    ]
