# Generated by Django 5.2.6 on 2025-09-25 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_clientesauditoria'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clientesauditoria',
            table='CLIENTES_AUDITORIA_TB',
        ),
    ]
