# Generated by Django 5.2.6 on 2025-09-25 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_clientesauditoria_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientesauditoria',
            options={'managed': False},
        ),
    ]
