# Generated by Django 5.2.6 on 2025-09-26 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_clientesauditoria_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientesauditoria',
            options={},
        ),
    ]
