# Generated by Django 5.2.6 on 2025-09-26 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_clientesauditoria_options'),
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientesauditoria',
            name='cliente',
            field=models.ForeignKey(blank=True, db_column='cliente_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='clientes.clientes'),
        ),
        migrations.AlterField(
            model_name='clientesauditoria',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuentas.usuarios'),
        ),
    ]
