# Generated by Django 6.0.3 on 2026-04-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(max_length=250)),
                ('imagen_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'Ubicaciones',
                'managed': True,
            },
        ),
    ]
